// Shared data for all layout versions — original texts from sergeenkov.com

export const blocks = [
    { type: 'paragraph', text: "I research the digital economy and share my findings publicly. I don't invest in or hold any cryptocurrencies, nor do I participate in any projects." },
    { type: 'photo' },
    { type: 'paragraph', text: "My works have been published in Forbes, CoinDesk, Blockworks and Cointelegraph." },
    { type: 'paragraph', text: "You can follow new articles via RSS or Twitter." },
    { type: 'paragraph', text: "My research has been cited in 43 academic papers by institutions including the World Economic Forum, Cato Institute, IEEE, Oxford University Press, and more." },
    { type: 'paragraph', text: "Full list of citations: sergeenkov.com/citations" },
    { type: 'paragraph', text: "My investigative work has been covered by CoinDesk, Cointelegraph, Decrypt, The Defiant, Motley Fool, Protos, and more. It has also been referenced in MetaMask's Crypto Security Report 2026, Coin Metrics' State of the Network, and Galaxy Research." },
    { type: 'paragraph', text: "Full list of media coverage: sergeenkov.com/coverage" },
    { type: 'paragraph', text: "The best way to contact me is via email andrey@sergeenkov.com. Alternatively you can use LinkedIn or Telegram." },
]

export const articles = [
    ["Address Poisoning Losses Surged 13x After Ethereum's Fusaka Upgrade", "Independent Research"],
    ["Curators of TheDAO's $220M Set a Precedent for Using Owners' Funds for Their Own Ends", "Independent Research"],
    ["Will TheDAO's $220M Security Fund Actually Make Ethereum Safer?", "Independent Research"],
    ["Record-High Activity in Ethereum Network Caused by Address Poisoning Attacks", "Independent Research"],
    ["Stop Pretending Technical And Human Vulnerabilities Are Separate Things", "Cointelegraph"],
    ["Why 2025 May Be The Right Time To Create National Bitcoin Reserves", "Forbes"],
    ["What Math Problems Do Bitcoin Miners Really Solve", "Forbes"],
    ["What Is A Bitcoin Node And How To Run One", "Forbes"],
    ["Tether Discontinues EURT And Sets Deadline For Token Redemption", "Forbes"],
    ["Understanding Polymarket And Prediction Markets", "Forbes"],
    ["How To Get First Funding For Web3", "Forbes"],
    ["What You Need To Know Before Buying Your First Bitcoin", "Forbes"],
    ["Russia Approves Cryptocurrency Tax Framework", "Forbes"],
    ["Crypto Fear And Greed Index", "Forbes"],
    ["Digital ID Trials Test Anonymous KYC For Mainland Chinese In Hong Kong", "Forbes"],
    ["Bitcoin Outperformed Nvidia, Google, Amazon In Rewards Per Risk In October 2024", "Forbes"],
    ["How To Mine Dogecoin", "Forbes"],
    ["Tesla, AMD And Nvidia Show Higher Volatility Than Bitcoin In October 2024", "Forbes"],
    ["MicroStrategy Announces $42 Billion Bitcoin Investment Plan", "Forbes"],
    ["What Is Ripple (XRP)", "Forbes"],
    ["Tesla Bitcoin Moves May No Longer Shake The Market", "Forbes"],
    ["Pennsylvania House Passes Crypto Protection Bill In Bipartisan Vote", "Forbes"],
    ["Russia Launches BRICS Mining Infrastructure Project", "Forbes"],
    ["What Are Stablecoins & How To Use Them", "Forbes"],
    ["China Bets On Massive Blockchain Infrastructure", "Forbes"],
    ["Legal Status Of Cryptocurrencies In Malaysia", "Forbes"],
    ["Ireland To Streamline Licensing Process For Crypto Businesses", "Forbes"],
    ["Louisiana Accepts First Cryptocurrency Payment For State Services", "Forbes"],
    ["How Bhutan Quietly Built $750 Million In Bitcoin Holdings", "Forbes"],
    ["UK Introduces Bill To Recognize Digital Assets As Personal Property", "Forbes"],
    ["Ryan Selkis Leaves Messari For New Political Initiative", "Forbes"],
    ["Crypto Unites Voters And Attracts Gamblers During The 2024 Elections", "Forbes"],
    ["How To Mine Bitcoin", "Forbes"],
    ["How To Buy Bitcoin: eToro", "Forbes"],
    ["Cryptocurrency Trading Causes Lower Quality Of Life And Higher Stress", "Forbes"],
    ["What Are Autonomous Economic Agents", "Forbes"],
    ["What Is NFT Art And How To Create It", "Forbes"],
    ["What Are AI-To-AI Crypto Transactions?", "Forbes"],
    ["Why TRX Has Grown 44% In The Last 90 Days", "Forbes"],
    ["What Are NFT DApps?", "Forbes"],
    ["How Volatile Is Bitcoin Compared To Other Assets", "Forbes"],
    ["What Is The Genesis Block Explained", "Cointelegraph"],
    ["Bonding Curves In DeFi Explained", "Cointelegraph"],
    ["Want To Improve Blockchain Infrastructure? Work Under Layer Two Solutions", "Cointelegraph"],
    ["Decentralized Parties: The Future Of On-Chain Governance", "Cointelegraph"],
    ["The Use Of Blockchain Tech Should Be More Environmentally Friendly", "Cointelegraph"],
    ["Institutional Investors Won't Take Bitcoin Mainstream — You Will", "Cointelegraph"],
    ["How To Manage Risk When Trading Cryptocurrency", "CoinDesk"],
    ["What Are Dynamic NFTs? Understanding The Evolving NFT", "CoinDesk"],
    ["Web3 Marketing Tips", "CoinDesk"],
    ["NFT Project Launch Tips", "CoinDesk"],
    ["What Is Counterparty Risk In Crypto?", "CoinDesk"],
    ["Crypto Arbitrage Trading: How To Make Low-Risk Gains", "CoinDesk"],
    ["How Does Ethereum Staking Work?", "CoinDesk"],
    ["What Are Soulbound Tokens? The Non-Transferrable NFT Explained", "CoinDesk"],
    ["What Is NFT Wash Trading?", "CoinDesk"],
    ["Everything You Need To Know About Bitcoin ETFs", "CoinDesk"],
    ["What's The Crypto Travel Rule And What Does It Mean For You?", "CoinDesk"],
    ["What We Know So Far About SHIB: The Metaverse", "CoinDesk"],
    ["What Is PancakeSwap? Here's How To Start Using It", "CoinDesk"],
    ["Want To Play Axie Infinity? Here's What You Need To Know", "CoinDesk"],
    ["How To Check Your Ethereum Transaction", "CoinDesk"],
    ["What's The Story Behind Bored Ape Yacht Club Creator Yuga Labs?", "CoinDesk"],
    ["Bitcoin Mining Difficulty: Everything You Need To Know", "CoinDesk"],
    ["Investing In Crypto: Alternatives To Bitcoin And Ether", "CoinDesk"],
    ["OpenSea Marketplace: How To Buy, Sell And Mint NFTs", "CoinDesk"],
    ["How To Buy Crypto On The Apps You Already Have", "CoinDesk"],
    ["What Is Bitcoin?", "CoinDesk"],
    ["What Is A Crypto Airdrop?", "CoinDesk"],
    ["Crypto Discord: Where To Go, What To Know", "CoinDesk"],
    ["Top 6 Crypto Passive Income Generators For 2021", "CoinDesk"],
    ["Someone Gave You Crypto As A Gift. Now What?", "CoinDesk"],
    ["Investing In Meme Coins: 3 Things Every Crypto Trader Should Know", "CoinDesk"],
    ["How To Buy A Tom Brady NFT", "CoinDesk"],
    ["Shiba Inu (SHIB): A Complete Beginner's Guide", "CoinDesk"],
    ["What Is ShibaSwap?", "CoinDesk"],
    ["5 Ways To Earn Passive Income From NFTs", "CoinDesk"],
    ["What Is CityCoins And How Does It Work?", "CoinDesk"],
    ["What Is Cryptocurrency?", "CoinDesk"],
    ["How To Buy Shiba Inu Coin (SHIB)", "CoinDesk"],
    ["Paying Off Student Loans? You Can Do It With Crypto", "CoinDesk"],
    ["What Is A Perpetual Swap Contract?", "CoinDesk"],
    ["How To Send Bitcoin Tips On Twitter", "CoinDesk"],
    ["China Crypto Bans: A Complete History", "CoinDesk"],
    ["5 Reasons Why Bitcoin Remains Below $50,000", "CoinDesk"],
    ["What Is A Bitcoin Futures ETF?", "CoinDesk"],
    ["How To Set Up A Bitcoin Miner", "CoinDesk"],
    ["How Does Ethereum Work?", "CoinDesk"],
    ["Solana", "CoinDesk"],
    ["What Is An Automated Market Maker?", "CoinDesk"],
    ["A Beginner's Guide To Atomic Swaps", "CoinDesk"],
    ["What Does Liquidation Mean And How To Avoid It", "CoinDesk"],
    ["Crypto Has An Influencer Problem", "Blockworks"],
    ["Gold, Bitcoin Or Notes: Staying Safe During Periods Of Economic Uncertainty", "Investing.com"],
    ["Bringing Machine Learning Closer to Clients, Will Blockchain Eliminate Barriers?", "Investing.com"],
    ["How Does Ethereum Staking Work?", "Nasdaq"],
    ["What Is an Automated Market Maker?", "Nasdaq"],
    ["A Beginner's Guide to Atomic Swaps", "Nasdaq"],
    ["Decentralized Parties Poised To Bring Blockchain To Politics", "Entrepreneur"],
    ["Common Mistakes That May Cause Investors To Walk Away", "Entrepreneur"],
    ["DeFi Is The New Lemonade Stand", "Entrepreneur"],
    ["You Can Leverage Cryptocurrencies To Upset The Balance Of Power", "Entrepreneur"],
    ["Rammstein Soloist Till Lindemann Accused of Illegal NFT Sales of Hermitage Museum Images", "CoinMarketCap"],
    ["What's Russia Up To? A Weekly Russian Crypto News Recap", "CoinMarketCap"],
    ["Cryptocurrency Market Cap Reclaims $2 Trillion as Market Rebounds", "CoinMarketCap"],
    ["How Bitcoin Miners Operate", "CoinMarketCap"],
    ["5 of the Biggest Crypto Ponzi Schemes", "CoinMarketCap"],
    ["Who Are Bitcoin Core's Developers?", "CoinMarketCap"],
    ["What Is Dollar-Cost Averaging (DCA)?", "CoinMarketCap"],
    ["Crypto Is Not Anonymous: How Criminals Are Caught on the Blockchain", "CoinMarketCap"],
    ["The Beginner's Guide to ERC20 Tokens and Addresses", "CoinMarketCap"],
    ["What Is Plasma Finance?", "CoinMarketCap"],
    ["Crypto's Role in Times of Political and Economic Uncertainty", "CoinMarketCap"],
    ["What Is Smart Contract Risk?", "CoinMarketCap"],
    ["What Is Coin98?", "CoinMarketCap"],
    ["What Is Polkaswap?", "CoinMarketCap"],
    ["What Is Polkarare?", "CoinMarketCap"],
    ["What Is Safe Earth?", "CoinMarketCap"],
    ["How to Mine Ethereum", "CoinMarketCap"],
    ["SEC Revises Stance on Digital Asset Classification", "CoinMarketCap"],
    ["Coinbase Halts Issuance of New Loans on Coinbase Borrow", "CoinMarketCap"],
    ["French Senate Considers Proposal to Allow Influencers to Promote Cryptocurrencies", "CoinMarketCap"],
    ["Study Finds 36% of Top Crypto Projects Silent on Blogging This Year", "CoinMarketCap"],
    ["Texas Securities Board Targets Alleged AI-Powered Crypto Scam", "CoinMarketCap"],
    ["Australian Crypto Exchange Coinjar Initiates US Expansion", "CoinMarketCap"],
    ["Poloniex To Pay $76 Million Fine for Sanctions Violation Charges", "CoinMarketCap"],
    ["Revolut Expands Crypto Investment Services to Brazil", "CoinMarketCap"],
    ["Level Finance Confirms $1 Million Exploit Due to Software Bug", "CoinMarketCap"],
    ["Binance Japan To Launch in June Following Acquisition of TaoTao", "CoinMarketCap"],
    ["Sotheby's Launches On-Chain Secondary NFT Marketplace", "CoinMarketCap"],
    ["MicroStrategy Reports Increased Revenue in Q1 2023 and Maintains Bitcoin Strategy", "CoinMarketCap"],
    ["Binance Launchpool Adds SUI Token: Staking BNB and TUSD for Rewards", "CoinMarketCap"],
    ["Ex-OpenSea Employee Accused of Profiting from NFT Insider Trading", "CoinMarketCap"],
]
